services:
  - type: web
    name: django-backend
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn myproject.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: django-backend.onrender.com
      - key: REDIS_URL
        fromService:
          type: redis
          name: django-redis
          property: connectionString

  - type: redis
    name: django-redis
    plan: starter
    ipAllowList: [] 