"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

from pathlib import Path
import re
import os
import environ
from django.core.exceptions import DisallowedRedirect

# Initialize environment variables
env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Function to allow custom URL schemes like 'voiceorderapp://'
def allow_custom_schemes(url):
    if url.startswith("voiceorderapp://"):
        return url
    raise DisallowedRedirect(f"Unsafe redirect to URL with protocol '{url.split(':')[0]}'")

# Monkey patch Django's HttpResponseRedirect validation
from django.http.response import HttpResponseRedirect
HttpResponseRedirect.allowed_schemes = ["http", "https", "voiceorderapp"]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY', default='django-insecure-_0jd6r-d@t_j5harf&v-2m(-_xgcm0+f8b!hl6zy=l*juys)-@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG', default='False') == 'True'

SECURE_REDIRECT_EXEMPT_SCHEMES = [
    "voiceorderapp",  # Allow your custom app scheme
]

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['voiceorderapp','192.168.19.50','192.168.10.14','192.168.131.50', '192.168.130.50' ,'localhost', '127.0.0.1','192.168.100.50','*','192.168.18.128','192.168.213.50','172.16.0.1','192.168.8.50','*'])
VALID_REDIRECT_REGEX = re.compile(r"^(http|https|voiceorderapp)://")

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'transcribe',
    'corsheaders',
    'rest_framework',
    'django_extensions',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Add this for static files
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Add CORS middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'myproject.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DATABASE_NAME', default='django_db'),
        'USER': env('DATABASE_USER', default='django_user'),
        'PASSWORD': env('DATABASE_PASSWORD', default=''),
        'HOST': env('DATABASE_HOST', default='localhost'),
        'PORT': env('DATABASE_PORT', default='5432'),
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Firebase Configuration - Use environment variables in production
FIREBASE_CREDENTIALS = env.dict('FIREBASE_CREDENTIALS', default={})

ASGI_APPLICATION = 'myproject.asgi.application'

# Channel Layers for WebSocket support
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            "hosts": [env('REDIS_URL', default='redis://127.0.0.1:6379')],
        },
    },
}

# CORS settings
CORS_ALLOW_ALL_ORIGINS = True  # For development - configure properly for production
CORS_ALLOW_CREDENTIALS = True

# JAZZCASH Configuration
JAZZCASH_MERCHANT_ID = env('JAZZCASH_MERCHANT_ID', default='MC148195')
JAZZCASH_PASSWORD = env('JAZZCASH_PASSWORD', default='t233vzg7fz')
JAZZCASH_INTEGRITY_KEY = env('JAZZCASH_INTEGRITY_KEY', default='wzu8tex9us')
JAZZCASH_RETURN_URL = env('JAZZCASH_RETURN_URL', default='mehakjaved.com')

# CSRF settings
CSRF_COOKIE_DOMAIN = env('CSRF_COOKIE_DOMAIN', default='192.168.18.128')
CSRF_COOKIE_PATH = "/"
CSRF_COOKIE_SAMESITE = "None"
CSRF_COOKIE_SECURE = False

# Stripe Configuration
STRIPE_SECRET_KEY = env('STRIPE_SECRET_KEY', default='')
STRIPE_PUBLISHABLE_KEY = env('STRIPE_PUBLISHABLE_KEY', default='')
STRIPE_WEBHOOK_SECRET = env('STRIPE_WEBHOOK_SECRET', default='')

# Security settings for production
if not DEBUG:
    SECURE_SSL_REDIRECT = True
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY' 